name: Docker

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: docker_open5gs
            context: base
            file: Dockerfile
          - image: docker_kamailio
            context: ims_base
            file: Dockerfile
          - image: docker_srslte
            context: srslte
            file: Dockerfile
          - image: docker_srsran
            context: srsran
            file: Dockerfile
          - image: docker_ueransim
            context: ueransim
            file: Dockerfile
          - image: docker_dns
            context: dns
            file: Dockerfile
          - image: docker_mysql
            context: mysql
            file: Dockerfile
          - image: docker_pyhss
            context: pyhss
            file: Dockerfile
          - image: docker_osmomsc
            context: osmomsc
            file: Dockerfile
          - image: docker_osmohlr
            context: osmohlr
            file: Dockerfile
          - image: docker_metrics
            context: metrics
            file: Dockerfile
          - image: docker_rtpengine
            context: rtpengine
            file: Dockerfile
          - image: docker_oai_enb
            context: oai
            file: enb_dockerfile
          - image: docker_oai_gnb
            context: oai
            file: gnb_dockerfile

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true

